Zoo/Models/Animal.cs
using System;

namespace Zoo.Models
{
    public abstract class Animal
    {
        private int energy;

        public int Id { get; set; }

        public string Name { get; set; }

        public abstract int MaxEnergy { get; }

        public int CurrentEnergy
        {
            get => energy;
            set
            {
                energy = Math.Clamp(value, 0, MaxEnergy);
            }
        }

        public abstract void Eat();

        public abstract void UseEnergy();
    }
}

Zoo/Models/Elephant.cs
namespace Zoo.Models
{
    public class Elephant : Animal
    {
        public override int MaxEnergy => 10000;

        public Elephant(string name)
        {
            Name = name;
            CurrentEnergy = 10;
        }

        public override void Eat()
        {
            CurrentEnergy += 1250;
        }

        public override void UseEnergy()
        {
            CurrentEnergy -= 5;
        }
    }
}

Zoo/Models/Lion.cs
namespace Zoo.Models
{
    public class Lion : Animal
    {
        public override int MaxEnergy => 5000;

        public Lion(string name)
        {
            Name = name;
            CurrentEnergy = 10;
        }

        public override void Eat()
        {
            CurrentEnergy += 625;
        }

        public override void UseEnergy()
        {
            CurrentEnergy -= 10;
        }
    }
}

Zoo/Models/Monkey.cs
namespace Zoo.Models
{
    public class Monkey : Animal
    {
        public override int MaxEnergy => 2000;

        public Monkey(string name)
        {
            Name = name;
            CurrentEnergy = 20;
        }

        public override void Eat()
        {
            CurrentEnergy += 250;
        }

        public override void UseEnergy()
        {
            CurrentEnergy -= 2;
        }
    }
}

Zoo/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Zoo.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Zoo/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Zoo.Animals;
using Zoo.Services;

namespace Zoo.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly AnimalService _animalService;
        private Timer timer;

        public List<Animal> Animals { get; set; }

        public SelectList ListOfAnimals {get; set;}

        [BindProperty(SupportsGet = true)]
        public string SelectedAddAnimal { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SelectedFeedAnimal { get; set; }

        public IndexModel(ILogger<IndexModel> logger, AnimalService animalService)
        {
            _logger = logger;
            _animalService = animalService;
            Animals = _animalService.GetAnimals();
            ListOfAnimals = new SelectList(_animalService.GetAnimalTypeNames());
        }

        public void OnGet()
        {
            StartTimer();
        }

        public void OnPostAdd([FromBody] AnimalDto animal)
        {
            var name = animal.Name;
            if (name is null)
            {
                return;
            }

            Type type = Type.GetType($"Zoo.Animals.{animal.Type}");         
            _animalService.AddAnimal((Animal)Activator.CreateInstance(type, name));
        }

        public class AnimalDto
        {
            public string Name { get; set; }
            public string Type { get; set; }
        }

        public void OnPostFeed([FromBody]string a)
        {
            Type type = Type.GetType($"Zoo.Animals.{a}");
            IEnumerable animals = _animalService.GetAnimals().Where(x => x.GetType() == type);
            foreach (Animal animal in animals)
            {
                animal.Eat();
            }
        }


        public void StartTimer()
        {
            timer = new Timer(UseEnergy, null, 10, 500);
        }

        public void UseEnergy(object _)
        {
            foreach(Animal animal in Animals)
            {
                animal.UseEnergy();
            }
        }

        
        //public  void OnPostFeeding([FromBody] string animal)
        //{

        //    Type type = Type.GetType($"Zoo.Animals.{animal}");
        //    IEnumerable animals = _animalService.GetAnimals().Where(x => x.GetType() == type);
        //    foreach (Animal a in animals)
        //    {
        //        a.Eat();
        //    }
        //}


        public PartialViewResult OnGetAnimalPartial()
        {
            return Partial("_AnimalPartial", Animals);
        }
    }
}

Zoo/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Zoo.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Zoo/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div>
    <form asp-page-handler="add" method="post">
        Add animal: <select asp-for="SelectedAddAnimal" asp-items="@Model.ListOfAnimals"></select>
        <input type="text" name="name" style="width: 130px" />
        <button id="Add" type="button" onclick="add()" class="btn btn-primary" style="width: 130px">Add</button>
    </form>
    <form asp-page-handler="feed" method="post">
        Feed animal: <select asp-for="SelectedFeedAnimal" asp-items="@Model.ListOfAnimals"></select>
        <button id="Feed" type="button" onclick="feed()" class="btn btn-primary" style="width: 130px" name="type" value="all">Feed</button>
    </form>
</div>
<div id="reload">

</div>


@section scripts {
    <script>
        function foo() {
            $('#reload').load('/Index?handler=AnimalPartial')
        }

        window.onload = function () {
            setInterval(foo, 500);
        }

        //$.ajax({

        //    url: '/?handler=Feed',
        //    //data: JSON.stringify(postData), //your data
        //    type: 'POST',
        //    contentType: 'application/json',
        //    dataType: 'json',

        //    success: function (result) {
        //        alert(result);  //do something if successful
        //    },
        //    complete: function () {
        //        //do something on complete
        //    },
        //    failure: function (err) {
        //        alert(err); // Display error message
        //    }
        //});

        function add() {
            var type = $('#SelectedAddAnimal').val();
            var name = $('input').val();
            var animal = {"Name":name,"Type":type};
            $.ajax({
                url: '/?handler=Add',
                type: 'POST',
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("RequestVerificationToken",
                        $('input:hidden[name="__RequestVerificationToken"]').val());
                },
                data: JSON.stringify(animal),
                success: function (result) {
                    alert(result)
                },
                complete: function () {
                    //do something on complete
                },
                failure: function (err) {
                    alert(err); // Display error message
                }
            });
        }

        function feed() {
            var animal = $('#SelectedFeedAnimal').val();
            $.ajax({
                url: '/?handler=Feed',
                type: 'POST',
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("RequestVerificationToken",
                        $('input:hidden[name="__RequestVerificationToken"]').val());
                },
                data: JSON.stringify(animal),
                success: function (result) {
                    alert(result)
                },
                complete: function () {
                    //do something on complete
                },
                failure: function (err) {
                    alert(err); // Display error message
                }
            });
        }
                        //var issue = JSON.stringify(this.swalForm);
                        //$.ajax({
                        //    type: "POST",
                        //    url: "../api/Issues",
                        //    contentType: "application/json; charset=utf-8",
                        //    beforeSend: function (xhr) {
                        //        xhr.setRequestHeader("RequestVerificationToken",
                        //            $('input:hidden[name="__RequestVerificationToken"]').val());
                        //    },
                        //    dataType: "json",
                        //    data: issue,
                        //    error: function (xhr) {
                        //        alert('Error: ' + xhr.statusText);
                        //    },
                        //    success: function (msg) {
                        //        console.log(msg.result);
                        //    }
                        //});

                        //$.ajax({
                        //    type: "POST",
                        //    url: "/Index?handler=Feed",
                        //    contentType: "application/json; charset=utf-8",
                        //    dataType: "json",
                        //    success: function (response) {
                        //        var dvItems = $("#dvPostItems");
                        //        dvItems.empty();
                        //        $.each(response, function (i, item) {
                        //            var $tr = $('<li>').append(item).appendTo(dvItems);
                        //        });
                        //    },
                        //    failure: function (response) {
                        //        alert(response);
                        //    }
                        //});




    </script>
}

Zoo/Pages/Shared/_AnimalPartial.cshtml
@model List<Zoo.Animals.Animal>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Animal
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].CurrentEnergy)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var animal in Model)
        {
            <tr>
                <td>
                    @animal.GetType().Name
                </td>
                <td>
                    @animal.Name
                </td>
                <td>
                    @animal.CurrentEnergy
                </td>
            </tr>
        }
    </tbody>
</table>

Zoo/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Zoo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-page="/Index">Zoo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Zoo - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>